from sqlalchemy import delete, select

from app.core.database import SessionLocal
from app.ingestion.eligibility_extractor import extract_eligibility_rules
from app.models.eligibility_rule import EligibilityRule
from app.models.opportunity import Opportunity


def get_eligibility_text(opportunity: Opportunity) -> str | None:
    """
    Extract the eligibility section from the normalized opportunity
    description.

    AICTE descriptions are stored in sections such as:

        Eligibility: B.Tech., B.E., Equivalent

    NSP descriptions contain the complete official scholarship
    information. We use the text available in the stored record and
    only create rules when recognizable requirements are present.
    """

    description = opportunity.description or ""

    marker = "Eligibility:"

    if marker in description:
        text = description.split(marker, 1)[1]

        # Stop at the next known section where possible.
        section_markers = [
            "\n\nResponsibilities:",
            "\n\nSkills:",
            "\n\nMode:",
            "\n\nDuration:",
            "\n\nPerks:",
        ]

        for section_marker in section_markers:
            if section_marker in text:
                text = text.split(section_marker, 1)[0]

        return text.strip()

    # NSP records don't necessarily have an explicit "Eligibility:"
    # section. The entire description is searchable by the extractor.
    if opportunity.source_key == "NATIONAL_SCHOLARSHIP_PORTAL":
        return description

    return None


def rule_signature(rule: dict) -> tuple:
    """
    Create a stable signature so identical rules aren't inserted twice.
    """

    return (
        rule["rule_type"],
        rule["field_name"],
        rule["operator"],
        rule["expected_value"],
    )


def populate_eligibility_rules() -> None:
    db = SessionLocal()

    try:
        opportunities = db.scalars(
            select(Opportunity)
            .where(
                Opportunity.source_key.in_(
                    [
                        "AICTE_INTERNSHIP_PORTAL",
                        "NATIONAL_SCHOLARSHIP_PORTAL",
                    ]
                )
            )
            .order_by(Opportunity.id)
        ).all()

        print("=" * 70)
        print("APTORA ELIGIBILITY RULE POPULATION")
        print("=" * 70)
        print(f"Real opportunities found: {len(opportunities)}")
        print()

        inserted = 0
        skipped = 0
        no_rules = 0
        replaced = 0

        rule_counts: dict[str, int] = {}

        for index, opportunity in enumerate(opportunities, start=1):

            eligibility_text = get_eligibility_text(opportunity)

            if not eligibility_text:
                no_rules += 1
                continue

            extracted_rules = extract_eligibility_rules(
                eligibility_text
            )

            if not extracted_rules:
                no_rules += 1
                continue

            # Remove existing rules for this opportunity so a fresh
            # import always reflects the latest source information.
            existing_rules = db.scalars(
                select(EligibilityRule).where(
                    EligibilityRule.opportunity_id == opportunity.id
                )
            ).all()

            if existing_rules:
                for existing_rule in existing_rules:
                    db.delete(existing_rule)

                db.flush()
                replaced += len(existing_rules)

            # Prevent duplicates generated by overlapping patterns.
            seen_signatures: set[tuple] = set()

            for rule in extracted_rules:
                signature = rule_signature(rule)

                if signature in seen_signatures:
                    continue

                seen_signatures.add(signature)

                eligibility_rule = EligibilityRule(
                    opportunity_id=opportunity.id,
                    rule_type=rule["rule_type"],
                    field_name=rule["field_name"],
                    operator=rule["operator"],
                    expected_value=rule["expected_value"],
                    description=rule["description"],
                    is_mandatory=rule["is_mandatory"],
                )

                db.add(eligibility_rule)

                inserted += 1

                rule_type = rule["rule_type"]
                rule_counts[rule_type] = (
                    rule_counts.get(rule_type, 0) + 1
                )

            if index % 100 == 0:
                db.commit()

                print(
                    f"Processed {index}/{len(opportunities)} | "
                    f"Rules inserted: {inserted} | "
                    f"No rules: {no_rules}",
                    flush=True,
                )

        db.commit()

        total_rules = db.scalar(
            select(EligibilityRule.id).limit(1)
        )

        actual_rule_count = len(
            db.scalars(select(EligibilityRule)).all()
        )

        opportunities_with_rules = len(
            db.scalars(
                select(
                    EligibilityRule.opportunity_id
                ).distinct()
            ).all()
        )

        print()
        print("=" * 70)
        print("ELIGIBILITY POPULATION COMPLETE")
        print("=" * 70)

        print(f"Opportunities processed : {len(opportunities)}")
        print(f"Rules inserted         : {inserted}")
        print(f"Old rules replaced     : {replaced}")
        print(f"No rules extracted     : {no_rules}")
        print(f"Final rule count       : {actual_rule_count}")
        print(
            f"Opportunities with rules: "
            f"{opportunities_with_rules}"
        )

        print()
        print("RULE BREAKDOWN")
        print("-" * 70)

        if rule_counts:
            for rule_type, count in sorted(rule_counts.items()):
                print(f"{rule_type:<25} {count}")
        else:
            print("No eligibility rules were extracted.")

        print("=" * 70)

    except Exception:
        db.rollback()
        raise

    finally:
        db.close()


if __name__ == "__main__":
    populate_eligibility_rules()