"""add opportunity source identity

Revision ID: 97f76f88e57d
Revises: d474cc110b19
Create Date: 2026-09-07 18:39:24.649729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97f76f88e57d'
down_revision: Union[str, Sequence[str], None] = 'd474cc110b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('opportunities', sa.Column('source_key', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_opportunities_external_id'), 'opportunities', ['external_id'], unique=False)
    op.create_index(op.f('ix_opportunities_source_key'), 'opportunities', ['source_key'], unique=False)
    op.create_unique_constraint('uq_opportunity_source_external', 'opportunities', ['source_key', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_opportunity_source_external', 'opportunities', type_='unique')
    op.drop_index(op.f('ix_opportunities_source_key'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_external_id'), table_name='opportunities')
    op.drop_column('opportunities', 'source_key')
    op.drop_column('opportunities', 'external_id')
    # ### end Alembic commands ###
