"""add saved opportunities

Revision ID: d474cc110b19
Revises: bda807307a5a
Create Date: 2026-09-07 15:29:46.394611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd474cc110b19'
down_revision: Union[str, Sequence[str], None] = 'bda807307a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'opportunity_id', name='uq_saved_opportunity_user')
    )
    op.create_index(op.f('ix_saved_opportunities_id'), 'saved_opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_saved_opportunities_opportunity_id'), 'saved_opportunities', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_saved_opportunities_user_id'), 'saved_opportunities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_opportunities_user_id'), table_name='saved_opportunities')
    op.drop_index(op.f('ix_saved_opportunities_opportunity_id'), table_name='saved_opportunities')
    op.drop_index(op.f('ix_saved_opportunities_id'), table_name='saved_opportunities')
    op.drop_table('saved_opportunities')
    # ### end Alembic commands ###
