"""add gender to profiles

Revision ID: eddf2bb66e8c
Revises: 97f76f88e57d
Create Date: 2026-09-07 20:25:13.665346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eddf2bb66e8c'
down_revision: Union[str, Sequence[str], None] = '97f76f88e57d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('gender', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_profiles_state'), 'profiles', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_state'), table_name='profiles')
    op.drop_column('profiles', 'gender')
    # ### end Alembic commands ###
